### ISSUE TITLE
No rule to make target 'parquet.bc', needed by 'all'.

### ISSUE THREAD

**Issue by ch-peterspiro** [zilder/parquet_fdw#1]
Hi, it's great to have found this extension.  I'm trying build it, but getting the following error from make.  Any suggestions?  Thanks!

`
% make

g++ -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -std=c++11 -O0 -ggdb3 parquet_impl.cpp  -c -fPIC -L/usr/lib/x86_64-linux-gnu  -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-6.0/lib  -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed  -lpgcommon -lpgport -lpthread -lselinux -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -ledit -lrt -lcrypt -ldl -lm  -o parquet.o
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o parquet_fdw.o parquet_fdw.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -shared -o parquet_fdw.so parquet.o parquet_fdw.o  -L/usr/lib/x86_64-linux-gnu  -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-6.0/lib  -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed  -lm -lstdc++ -lparquet -larrow
make: *** No rule to make target 'parquet.bc', needed by 'all'.  Stop.
`

**Comment by ch-peterspiro** [comment]
FYI, seems the issue is specific to pg11, as mentioned here: https://github.com/plv8/plv8/issues/304#issuecomment-426035141

Works fine on pg10.6

**Comment by zilder** [comment]
Hi @ch-peterspiro,

Thank you for your report. I haven't yet tried it with pg11, but will do tomorrow. It looks like you are right about llvm support issue.

**Comment by zilder** [comment]
Pushed a fix to the `master` branch. Can you please check if it works for you?

**Comment by ch-peterspiro** [comment]
Thanks for the quick fix.  It builds fine now for version 11.1.

Though on 11.1 it still has this issue https://github.com/zilder/parquet_fdw/issues/2 for me (as it does on 10.6 but not 10.4).
