### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jakebolewski** [zilder/parquet_fdw#6]
I came across this repo while looking for examples of an FDW / Postgres extension with a C++ project and it seems generally useful but didn't want to look too hard because there is no license.  Could you clarify / add this info?

**Comment by zilder** [comment]
Hi @jakebolewski,

thanks for the question. I've added a license to the project, it is a standard postgres license.

**Comment by jakebolewski** [comment]
Thanks @zilder! This is one of the easiest to follow Postgres FDW example projects I've seen as someone who is new to the ecosystem.

**Comment by zilder** [comment]
Thanks : ) I just want to point out that i'm not exactly a c++ programmer, but i had to use it because of `libarrow` and `libparquet`. So most of the code is still written in c-style.

**Comment by lussman3** [comment]
It's truly aweszome that this great project is going to be Postgres
licensed.   I'm a big fan and hope to be able to contribute in some
meaningful way going forward.

--Denis Lussier
  Longtime Postgres Community Member
  Product Manager for Postgres at AWS
