### ISSUE TITLE
multiple Parquet files

### ISSUE THREAD

**Issue by benjdv** [zilder/parquet_fdw#7]
Parquet are often slitted (partition) in multiple subfile (with the same struct).
So, it will be great to have the possibility to create a foreign table from these multiple files (and not having one foreign table by Parquet).
Example:
./data_pqt/0_0_1.parquet
./data_pqt/0_0_2.parquet
./data_pqt/0_0_2.parquet

`create foreign table...
options (
    filename './data_pqt/*.parquet'
);`
or (directly with the directory)
`create foreign table...
options (
    filename './data_pqt'
);`

**Comment by zilder** [comment]
Hi @benjdv,

thanks for the suggestion. We decided not to do that just yet so as not to overcomplicate things. Currently we use postgres partitioning to combine several parquet tables. It already provides some nice features like partition pruning and parallel query execution.

**Comment by benjdv** [comment]
Please find a function that will help to import all sub-parquet with inheritance. hoping that it can help someone.
Some improvements can of course be made.
```SQL
CREATE OR REPLACE FUNCTION public.import_parquet(parquet_path TEXT, inherits_from TEXT, id_parquet TEXT DEFAULT '', drop_table BOOLEAN DEFAULT FALSE, create_table BOOLEAN DEFAULT true)
  RETURNS void AS
$BODY$
DECLARE
 fn TEXT;
 foreign_name TEXT;
BEGIN
 CREATE TEMP TABLE t_files(filename text) ON COMMIT DROP;
 EXECUTE format($$COPY t_files FROM PROGRAM 'find %s -maxdepth 1 -type f -name "*.parquet"'$$, parquet_path); -- Find the sub-Parquet file

 FOR fn IN (SELECT filename FROM t_files ) LOOP
  foreign_name:=inherits_from || '_' || id_parquet || '_' || (regexp_match(fn,'(?:.*/|^)([^/]*).parquet'))[1];
  IF drop_table THEN
   EXECUTE 'DROP FOREIGN TABLE IF EXISTS ' || quote_ident(foreign_name);
  END IF;
  IF create_table THEN
   EXECUTE 'CREATE FOREIGN TABLE ' || quote_ident(foreign_name) || ' ()'
   || ' INHERITS (' || quote_ident(inherits_from) || ')'
   || ' SERVER parquet_srv'
   || ' OPTIONS ('
   || '  filename ''' || fn || ''''
   || ' )';
  END IF;
  --RAISE INFO '% done', fn;
 END LOOP;
END;
$BODY$
  LANGUAGE plpgsql VOLATILE STRICT
  COST 1000;
ALTER FUNCTION public.import_parquet(TEXT, TEXT, TEXT, BOOLEAN, BOOLEAN)
  OWNER TO postgres;
-- Création/Import des Foreign Table
-- SELECT * FROM public.import_parquet('/tmp/exemple_pqt','m_exemple', 'EXDEMO', false, true, true);
```
